### PR TITLE
Portuguese translation of wegue

### PR DESCRIPTION
**Pull request by wljrodrigues**
Portuguese translation of wegue.

### CODE REVIEW

**Review by chrismayer — COMMENTED** [review]
Thanks @wljrodrigues for your translation! Very much appreciated :+1: 

The files within the `app/` folder are not thought to be committed to the main Wegue repository. It is reserved for the code of your custom Wegue application. The application inside the `app/` folder is filled by the npm-task `init:app` based on the `app-starter/` folder. 

So before merging this, your PR needs to be cleaned up, so the `app/` folder is no more part of the changes. When you revert `app/.gitignore` you shouldn't even be able to commit the content of the app folder. This is by design.
Would you please do this cleanup @wljrodrigues? Would be very nice. Afterwards I'd happily merge this. If you need some help ping us here.

**Comment by wljrodrigues** [comment]
Update complete: The ".gitignore" file in the "app/" directory has been restored to its original state, and the files in the "app/" folder have been cleaned up according to the instructions. I will proceed with creating the PR now. Thanks for your attention, Jakob.

**Comment by wljrodrigues** [comment]
@chrismayer  Thank you very much for the guidance. I have completed the requested procedures and am now submitting the corrected version for the PR.

**Comment by chrismayer** [comment]
@wljrodrigues the tests in CI pipeline are still faling. I created a Pull Request against your changeset https://github.com/wljrodrigues/wegue/pull/1, which fixes the tests. If you're happy with my PR please merge it and then this PR should be good to go.

**Review by chrismayer — APPROVED** [review]
Thanks again for providing this @wljrodrigues and for your ongoing effort based on the reviews :+1:

**Comment by wljrodrigues** [comment]
> Thanks again for providing this @wljrodrigues and for your ongoing effort based on the reviews 👍

@chrismayer thank you very much for the valuable guidance🤝

**Comment by chrismayer** [comment]
@sronveaux sure, would be great. Looking forward...

**Pull request merged**
