### PR TITLE
infoClick on multiple visible features/layers

### PR DESCRIPTION
**Pull request by enricofer**
The pull request is about a new infoclick feature allowing to browse between multiple features detected on map visible layers 
Screenshot (230)

### CODE REVIEW

**Comment by fschmenger** [comment]
Hi @enricofer,
thank you for the contribution!
I tested this briefly and it works well.

Could you please run `npm run lint:fix` once and commit the result.
Some more comments inline.

Greets Felix

**Comment by enricofer** [comment]
Hi here I am, sorry for the noise and thank for your work.

**Review by chrismayer — APPROVED** [review]
Really nice, thanks for this useful addition!

**Comment by chrismayer** [comment]
I had a quick look, what is wrong with the test: The line https://github.com/wegue-oss/wegue/blob/master/tests/unit/specs/components/infoclick/InfoClickWin.spec.js#L88 and following need to be changed to 

```js
map.forEachFeatureAtPixel = () => {
  vm.features.push([feat, layer]);
};
```
so the mock still reflects the current code.

**Comment by chrismayer** [comment]
Hi @enricofer , do you see a chance that you push this forward? No fronts, this is not meant to put pressure on you. I know everybody has a lot to do. But this feature is too cool, to hang around here ;-) If you currently do not have time to push this forward, which is no problem, I'd happily take over here and finish this. Thanks for any feedback and your great work so far!

**Comment by enricofer** [comment]
I apologize at that moment I didn't understand the meaning of the code and I forgot to update the PR

**Review by chrismayer — APPROVED** [review]
@enricofer no need to apologize, all good here :+1: Thanks for your ongoing effort. 

LGTM now, I am going to merge.

**Pull request merged**
