### PR TITLE
Update Vue to v2.7.14 LTS + Vuetify v2.6.15

### LINKED ISSUE #330: Upgrade to Vue 2 and Vuetify 2 LTS
Wegue should be upgraded to Vue 2 and Vuetify 2 LTS.

### PR DESCRIPTION
**Pull request by spwoodcock**
This PR is built on top of #320, to allow for an easier single merge.
Apologies for this non-standard approach, but I couldn't think of a better way - these updates are reliant on the previous PR commits.

Closes #330.

- I upgraded Vue, as in the title.
- Also upgraded vue-i18n to the latest Vue2 version.
- Vuetify was upgraded to `v2.6.15`. IMO, we shouldn't wait for Vuetify `v2.7` LTS to be released, as Vuetify development can be painfully slow. It shouldn't really matter as `2.7` seems to be focused on "backports and deprecations from v3.0.0 to help developers prepare for v3 upgrade".

**Additional considerations**:
- I pushed a version of **package-lock.json** generated from `npm install` using NPM v6, as v7 updates the lock file to `lockfileVersion: 2`. Ideally all developers should be using the same version of NPM, but this is hard to enforce. I considered updating `engines.npm` in **package.json** to have a maximum version and creating a `.npmrc` with `engine-strict: true`, but this may cause issues with downstream users.
  - NPM v6 can be used by running `npm install` inside a `node:14` docker container.
  - NPM v6 is from 2018, so in future we could update to NPM v7-8 (`lockfileVersion: 2`), or NPM v8 (`lockfileVersion: 3`).
- I also updated the **vue.config.js** `devServer.port` to `0.0.0.0`, as it allows more flexibility than `localhost`.

### CODE REVIEW

**Comment by fschmenger** [comment]
Hi Sam,
thanks for providing this. The next 2 weeks will be busy here, then I hopefully will find a time slot to have a closer look.

I don`t see any problem with PRs being built on top of each other, we used to follow the same approach with all the vue template upgrades. So, even if this incorporates #320, could you reopen #320 again? This will give us the opportunity to review and merge in changes in a more fine grained way. 

Cheers,
Felix

**Comment by spwoodcock** [comment]
No problem, I will re-open 👍 
This PR is superseded by #334.

**Comment by spwoodcock** [comment]
Merged `master` to only show specific commits - ready to test and merge.

**Comment by spwoodcock** [comment]
Closed in favour of #335

**Pull request closed without merging**
