### PR TITLE
Merge Vue CLI updates & upgrade to OpenLayers v6.15.7

### PR DESCRIPTION
**Pull request by spwoodcock**
**What is included:**
- First I have merged all Vue CLI PRs sequentially and resolved conflicts (#298, #297, #312, #314), great work @sronveaux! I hope this helps to save time in getting these great additions merged.
- Then I solved the remaining linting errors and upgraded to OpenLayers 6.7.0. I did some basic testing and couldn't find errors, so this could close #261.
- There are no breaking changes I can see in OpenLayers until v7, so I upgraded to v6.15.1, the last version prior.
- Upgrading to v7 would require some refactoring for removed methods: https://github.com/openlayers/openlayers/blob/main/changelog/upgrade-notes.md#700
- After merging this PR, implementing #290 would be possible.

**What I missed:**
- I couldn't get the Karma ChromeHeadless tests to work, as I run my coding environment inside a docker container.
I get (expected) errors related to system dbus and WebGL:
```
Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Passthrough is not supported, GL is disabled
```

### CODE REVIEW

**Comment by fschmenger** [comment]
Hi @spwoodcock,
great to see you already got going and thanks a lot for providing this so quickly! I`m currently a bit limited on time but I hope to have some time for testing here in the upcoming weeks.

Just for clarification: The vue-cli-5 upgrade has to go into Wegue v2, as it comes with new major versions of several dependencies like Webpack etc. So by incorporating the vue-cli upgrade PR, it has to go into v2 too obviously.

**Comment by spwoodcock** [comment]
Ah my bad! I thought it made sense to build this on the Vue CLI upgrades, as #261 was having errors due to outdated dependencies.

I don't think there is another solution due to conflicts with the geotiff library otherwise.

I hope this PR was helpful and will simplify the review for the combined Vue CLI changes.

**Comment by fschmenger** [comment]
Hi @spwoodcock. I finally found some time to test the OL v6.15.7 migration in Wegue and in a custom application. Everything works out of the box as intended. Looks like the OL guys did a clean job in semantic versioning, so I couldn`t find any breaking changes either. And a big thanks again to you for giving us a merged PR, so we can fiddle around with the upcoming changes much easier!

Regarding your comments above:
* The OL 7 migration seems to be a more complex job. For the very least I know of the tooltip functionality, which makes use of `Map::forEachLayerAtPixel`, which will eventually break and be cumbersome to work around. If you are interested to work on that (as part of a seperate PR) it`s obviously very much appreciated. :)
* I have no experience in running the IDE inside a docker container and accessing ChromeHeadless tests from there. Did you install it properly in the respective image? Here`s some info on [StackOverflow](https://stackoverflow.com/questions/43665276/how-to-run-google-chrome-headless-in-docker), not sure if it could be helpful?! 

@chrismayer: I have to point out that I only use a small subset of OL functionality. It would be desirable if you could verify it in one of your applications too, so we have a little broader coverage.

One final comment:
For the sake of a clean commit history, I propose that we rebase this one on master once the time has arrived - or just redo it by adjusting the OL version if simpler. Anyway, very nice to have this PR around for testing!

Cheers,
Felix

**Comment by spwoodcock** [comment]
Hi @fschmenger, thanks for getting back to me. 

Glad the PR was useful for testing. Like you say, feel free to rebase and merge, or close and re-create, as you prefer.

I'm made 4 commits, two related to fixing lint errors (preventing the app starting), two for a progressive ol upgrade.

**Comment by fschmenger** [comment]
Hi @spwoodcock,
I missed running the karma unit tests yesterday. Currently they don`t work for me either - however they do work in the underlying #314.

```
Uncaught ReferenceError: require is not defined
  at webpack://wegue/./node_modules/ol/Map.js?:4:30
  
  ReferenceError: require is not defined
      at eval (webpack://wegue/./node_modules/ol/Map.js?:4:30)
      at Module.<anonymous> (index.2854134847.js:755:1)
      at __webpack_require__ (index.2854134847.js:5023:42)
      at eval (webpack://wegue/./src/components/ol/Map.vue?./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use%5B0%5D!./node_modules/@vue/cli-service/node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options:10:35)
      at Object.<anonymous> (index.2854134847.js:748:1)
      at __webpack_require__ (index.2854134847.js:5023:42)
      at eval (webpack://wegue/./src/components/ol/Map.vue?:6:246)
      at Module.<anonymous> (index.2854134847.js:741:1)
      at __webpack_require__ (index.2854134847.js:5023:42)
      at eval (webpack://wegue/./src/components/ol/Map.vue?:7:91)
```

I assume there is some problem with OL using commonJS imports. However I`m not sure why this hits us in the unit tests and not on production build, and why it should be a problem with OL 6.15.7 but not with OL 6.4.3. 

@sronveaux Do you have any idea here? I tried to set `transpileDependencies` like I proposed in #314, that got rid of a bunch of warnings but at the end runs into the same problem.

**Comment by sronveaux** [comment]
Another way to debug this kind of laborious issue is to find the exact version of `OL` where the problem starts to occur, see what's new from the previous version and add the potential new dependency in the `tests/unit/index.js` as explained above... very frustrating to do...

**Comment by chrismayer** [comment]
> @chrismayer: I have to point out that I only use a small subset of OL functionality. It would be desirable if you could verify it in one of your applications too, so we have a little broader coverage.

I just tested this PR with our latest customer app, which uses some more OL functionality besides the common Wegue stuff. It really looks amazing and works quite well. I tested dev mode and production build without any problems. And upgrading was quite smooth, only `npm install`, making eslint happy due to some new rules and this thing is ready to fly :rocket: .

Great work everybody :muscle:

**Comment by spwoodcock** [comment]
Based on the discussions around fixing the unit tests, what are the two constants that require updating here?

Feel free to update my branch, or I can update in a few days when I'm back.

**Comment by fschmenger** [comment]
Hi @spwoodcock, I couldn`t push the fixes for the unit tests to your branch,
so I temporarily parked them in #331 2a451d9a960d458c52be51cab34821951ab32417.
Could you just pull it from there?

**Comment by spwoodcock** [comment]
@fschmenger done 👍

**Comment by spwoodcock** [comment]
I updated this to include the additional commits to #314 and the latest commit on master as of 26/04/2023 (c549872209600eb380fc46cf0bdec9ed53bb8ecf).

**Comment by spwoodcock** [comment]
I will close this PR in favour of #333.

**Comment by chrismayer** [comment]
This works quite well. Just tested again. 

The conflict is just a removed trailing whitespace in ` src/components/attributeTable/AttributeTableWin.vue`, so is easily fixable.

I am going to approve now.

**Comment by spwoodcock** [comment]
Thanks for the PR @chrismayer 👍

**Comment by spwoodcock** [comment]
Just in time for FOSS4G 😉

**Comment by chrismayer** [comment]
> Just in time for FOSS4G wink

Total coincidence, but certainly not bad at all :wink:

**Pull request merged**
